package-lock.json, package.json, src/Loader.js, src/Replicator.js, src/Store.js, src/parse-address.js
Fix replication related bugs.
Fix progress callbacks.
Use latest ipfs-log API.
Parse valid orbitdb path from dbname
Add snapshot saving and loading.
Process sync queues more efficiently.
Add close() to Store.
Add loadMoreFrom().
Add internal stats counters.
Change default max history to: all.
Remove obsolete dependencies.
=> Fix Replication

package.json, src/Store.js
Remove Keystore dependency
Remove Cache dependency
Delete local cache files upon drop
=> Refactor local cache

src/Store.js, src/replication-info.js
This PR will refactor the Store's internal replication status tracking.
=> Refactor replication status info

src/Store.js
Currently it's caching the last heads sent over from the peer. If this is malicious peer then those heads could overwrite valid heads sent from other peers. Putting in replicated allows only validated head entries to be written to cache(will also merge with other heads that the peer did not see, in case of a fractured network).
Note: there's also an issue currently where the return of the verify function is discarded and requires a Promise.reject to work, thereby discarding possible valid heads from an innocent passthrough peer(Should be an easy fix in ipfs-log).
=> Cache verified heads only.

package-lock.json, package.json, src/Replicator.js, src/Store.js
This PR updates store to use the latest ipfs-log
=> Feat/new ipfs log (wip)

src/Store.js
Fix orbit-db-store `sync` method, removing leftovers from the last refactoring
Changed `.then` to use `async/await`
We need a function to validate entries to be exposed by the log or maybe use one of the factory methods for that
Closes #34
=> Fix store sync method

package-lock.json, package.json
=> WIP: Use new access controller system

package-lock.json, package.json, src/Replicator.js, src/Store.js
=> Add linter

package-lock.json, package.json, src/Replicator.js, src/Store.js
Removes `cid` property from entries
=> remove cid prop

package-lock.json, package.json
upgrades ipfs-log and orbit-db-io to supprt ipfs@0.36.x
=> upgrade deps

package-lock.json, package.json, src/Store.js
Adds options to load cache before calling addOperation
Passes sortFn from options down to `ipfs-log`
=> load before append

.npmignore, package-lock.json
Removes redundant lines in `.npmignore`
=> delete unnecessary lines

src/Store.js
=> Final cache fixes for 0.22

src/Store.js
Removes setting the default directory in `options` 
removes `try/catch` block
=> remove default directory and try/catch

src/Store.js
Removes unused arguments and adds options object to `_addOperation`
=> Pass arguments as options object

package-lock.json, package.json, src/Store.js
https://github.com/orbitdb/orbit-db/issues/762
=> ready for js-ipfs 0.41

package-lock.json, package.json, src/Store.js
https://github.com/orbitdb/orbit-db/issues/737
adds a queue to _addOperation()
close() awaits for the queue to empty before resolving
=> _addOperation calls are serialized

README.md
Copied the extensive comments from `src/Index.js` in the Documentation.
The goal of this pull request is to create an easy to  use reference 
for Store developers. 
In order to do this, we have to create a reference of `Index` types and how to create your own.
=> Documentation for Store Developers

.github/workflows/codeql-analysis.yml, .github/workflows/npm-publish-next.yml, .github/workflows/npm-publish.yml
Just tried to contribute to continuous deployment as mentionned in [Orbit-DB](https://github.com/orbitdb/orbit-db/issues/899#issuecomment-89548647). Please let me know if I'm on the right track before I try the others!
For now I just copied to CD code from the example repositories. Not too sure how to run tests on orbit-db when orbit-db-store is modified, but if you can point me in the right direction I'd be happy to give it a try!
=> Try automating deployment

src/Store.js
Resolves point 2 of https://github.com/orbitdb/orbit-db/issues/906. Not too sure where and how to add a test to avoid future regressions though.
Thanks!
=> Close access controller on Store.close()
